# Edit the vars to create a new networkservice
# Cretaed by Remo Mattei matteir@vmwrae.com
- connection: local
  hosts: localhost
  collections:
  - vmware.alb
  vars_files:
     - creds.yml
     - pass.yml
  vars:
   segname: "active_standby"
   vcenter: "dc1_vCenter"
   ip1:  "100.64.130.103"
   networkservice_name: "remo_demo"
   username: "admin"
  tasks:
  - name: 'Create or Update NetworkService: floating_ip'
    avi_networkservice:
      name: "{{ networkservice_name }}"
      tenant_ref: "/api/tenant/?name={{ username }}"
      cloud_ref: "/api/cloud?name={{ vcenter }}"
      service_type: ROUTING_SERVICE
      routing_service:
        enable_routing: true
        floating_intf_ip:
        - addr: "{{ ip1 }}"
          type: V4
        enable_auto_gateway: true
      se_group_ref: "/api/serviceenginegroup/?name={{ segname }}"
      vrf_ref: /api/vrfcontext/?name=global
      avi_credentials: "{{ avi_credentials }}"
      state: present
      api_context: '{{avi_api_context | default(omit)}}'
      tenant: "{{ username }}"
