---
# Edit the vars to create a new application profile
# This needs to run after you created the SE Group
# Cretaed by Remo Mattei matteir@vmwrae.com
- connection: local
  hosts: localhost
  collections:
  - vmware.alb
  vars_files:
    - creds.yml
    - pass.yml
  vars:
   segname: "active_legacy"
   vcenter: "dc1_vCenter"
   username: "admin"
  tasks:
  - name: 'Create or Update ApplicationProfile: l4-preserve-client-ip'
    avi_applicationprofile:
      avi_credentials: "{{ avi_credentials }}"
      name: l4-preserve-client-ip
      type: APPLICATION_PROFILE_TYPE_L4
      tenant_ref: /api/tenant/?name=admin
      dos_rl_profile:
        dos_profile:
          thresh_period: 5
      tcp_app_profile: {}
      preserve_client_ip: true
      state: '{{ state | default(omit)}}'
      api_context: '{{avi_api_context | default(omit)}}'
      tenant: "{{ username }}"
