---
# Edit the vars to create a new application profile
# Cretaed by Remo Mattei matteir@vmwrae.com
- connection: local
  hosts: localhost
  collections:
  - vmware.alb
  vars:
   username: "admin"
   password: "HelloRemodemopasswordforavi"
   avi_version: "22.1.4"
   controller: "10.10.10.111"
   api_version: "22.1.4"
   segname: "as_legacy"
   vcenter: "vcenter"
  tasks:
  - name: 'Create or Update ApplicationProfile: l4-preserve-client-ip'
    avi_applicationprofile:
      name: l4-preserve-client-ip
      type: APPLICATION_PROFILE_TYPE_L4
      tenant_ref: /api/tenant/?name=admin
      dos_rl_profile:
        dos_profile:
          thresh_period: 5
      tcp_app_profile: {}
      preserve_client_ip: true
      controller: '{{ controller }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: '{{ state | default(omit)}}'
      api_version: "{{ api_version }}"
      api_context: '{{avi_api_context | default(omit)}}'
      tenant: "{{ username }}"
